spring:
  cloud:
    gateway:
      routes:
        - id: service-catalogs
          uri: lb://service-catalogs
          predicates:
            - Path=/api/catalogs/**
          filters:
            - StripPrefix=2
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - '*'
            allowedHeaders:
              - '*'
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allow-credentials: true
  application:
    name: service-gateway
server:
  port: 8085

eureka:
  client:
    registry-fetch-interval-seconds: 30
